# Generated by Django 5.2.6 on 2025-09-09 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_alter_booking_persons_alter_booking_tableno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='Menu',
        ),
    ]
